name: Publish Python Package

on: [push]

jobs:
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set tag version
        id: tag_version
        run: |
          tag=$(echo $GITHUB_REF | cut -d / -f 3)
          echo ::set-output name=version::${tag:1}

      - name: Install dependencies
        run: python3 -m pip install --upgrade build twine

      - name: Build project
        run: python3 -m build

      - name: Check build
        run: python3 -m twine check dist/*

      - name: Install leetcode-export
        run: sudo python3 setup.py install

      - name: Check that tag version matched Python package version
        run: |
          expected="leetcode-export ${{ steps.tag_version.outputs.version }}"
          actual=$(leetcode-export --version)
          echo expected=\"$expected\"
          echo actual=\"$actual\"
          [[ $expected == $actual ]]
